version: '3'
services:

  my-perl-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-perl-app
    environment:
      - PORT=3001
    volumes:
      - ./project/:/MyApp
    network_mode: 'host'
    # command: "unbuffer perl /MyApp/script/myapp_server.pl -p $PORT -r -d"
    command: "unbuffer perl /MyApp/script/myapp_server.pl --debug --fork --port 3001 --keepalive --restart --restart_delay 1"
